# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Welcome! Thank you for opening your first issue.
  TheCrafters001 will review the issue soon.
  Thank you for using Easy Butler!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request!
  TheCrafters001 will look over the changes soon.
  Make sure all your changes follower the Code of Conduct and Community Guidlines (if any)
  Thank you for using Easy Butler!

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request!
  Easy Butler will soon have your features in it!
  To see if your name was official added, check out ```contributors.md```!
  If your name is not in ```contributors.md```, create a issue, and it should be resolved.
  Thank you for using Easy Butler! 

# It is recommend to include as many gifs and emojis as possible
# Users authorized to run manual trop backports
authorizedUsers:
  - TheCrafters001
